apiVersion: v1
kind: Pod
metadata:
  name: frontend-service
  namespace: net-demo
  labels:
    app.kubernetes.io/name: frontend-service
spec:
  containers:
  - name: frontend-service
    image: httpd:alpine
    ports:
      - containerPort: 81
