apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-pod
spec:
  podSelector:
    matchLabels:
      app: backend-pod
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend-service