apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
  namespace: default
spec:
  containers:
  - name: secret-demo-pod
    image: httpd:latest
    env:
    - name: DB_USER
      valueFrom:
        configMapKeyRef:
          name: DB-Secret
          key: username
    -  name: DB_PASS
       valueFrom:
         configMapKeyRef:
           name: DB-Secret
           key: password
    ports:
    - containerPort:  80
