apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
  - name: demo
    image: nginx
    volumeMounts:
      -  name: secret-vol
         mountPath: "/etc/secret-data"
         readOnly: true
  volumes:
    -  name: secret-vol
       secret:
         secretName: db-secret



         
