apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: service-demo
spec:
  serviceAccountName: demo
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command: ["sleep", "3600"]