apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-binding
  namespace: service-demo
subjects:
-  kind: ServiceAccount
   name: demo-user
   namespace: service-demo
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io


  