apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
  namespace: hpa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: burner
        image: busybox:1.36
        command: ["sh", "-c","yes > dev/null & sleep=0.2; done" ]
        resources:
          requests:
            cpu: "200m"
            memory: "32Mi"
          limits:
            cpu: "500m"
            memory: "120Mi"  


